name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Format check
      run: npx prettier --check "src/**/*.js"
      
    - name: Run unit tests
      run: npm test
      
    - name: Build
      run: npm run build:app
      env:
        CI: false  # Prevents build failures on warnings
        
  # Uncomment when site is deployed and environment variables are configured
  # visual-tests:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   
  #   steps:
  #   - uses: actions/checkout@v4
  #   
  #   - name: Setup Node.js
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: 18
  #       cache: 'npm'
  #   
  #   - name: Install dependencies
  #     run: npm ci
  #     
  #   - name: Run Cypress visual tests
  #     uses: cypress-io/github-action@v6
  #     with:
  #       start: npm run develop
  #       wait-on: 'http://localhost:8000'
  #     env:
  #       GATSBY_AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}
  #       GATSBY_AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
  #       GATSBY_TABLE_NAME: ${{ secrets.TABLE_NAME }}